language: objective-c
osx_image: xcode7.3
script:
  - set -o pipefail
  - xcodebuild -workspace Airfield-Manager.xcworkspace -scheme Airfield-Manager -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
